### ISSUE TITLE
USER STORY: User Profile Creation

### ISSUE THREAD

**Issue by PjHurtig** [PjHurtig/Project-4#1]
EPIC: <epic>

As a **user** I can **create a profile** so that **I can login to the site**

**Acceptance Criteria**

- [ ]  The user can choose a username 
- [ ]  The user can choose a password
- [ ]  The user can login to the site
- [ ] The user can log out of the site

**Tasks**

- [ ] Create a login form 
- [ ] Create a registration form
- [ ] Authenticate users
- [ ] Add error handling
- [ ] Test functionality
